#  Copyright (c) 2005-2007 Andre Merzky (andre@merzky.net)
# 
#  Distributed under the Boost Software License, Version 1.0. 
#  (See accompanying file LICENSE or copy at 
#  http://www.boost.org/LICENSE_1_0.txt)

-include make.cfg

-include $(SAGA_MAKE_INCLUDE_ROOT)/saga.mk

distclean::
	@rm make.cfg

